"""Deep Research Agent package foundation."""

from .artifacts import ARTIFACT_SCHEMA_VERSION, build_artifact_payload
from .config import (
    AppConfig,
    CodexConfig,
    ModelProvider,
    OllamaNativeConfig,
    OllamaOpenAIConfig,
    OpenAIConfig,
    load_config,
)
from .evidence import EvidenceRecord, SearchEvidenceBatch, SearchFailure, collect_search_evidence
from .geography import (
    GeoAliasSuggestion,
    GeoScope,
    normalize_geography,
    suggest_geography_alias_update,
)
from .graph import (
    CHECKPOINT_SCHEMA_VERSION,
    GRAPH_TOPOLOGY,
    GraphRunResult,
    LocalCheckpointStore,
    LocalResearchGraph,
    ProspectRunBudget,
    build_graph,
    derive_prospect_run_budget,
    graph,
    inspect_thread,
    resume_thread,
    run_query,
)
from .models import (
    FallbackEvent,
    ModelPreflight,
    ModelPreflightError,
    ModelProviderStatus,
    ModelRequest,
    ModelResponse,
    build_model_client,
)
from .prospects import CitationValidationError, Prospect, ProspectCitation
from .search import FirecrawlProvider, SearchResult, YdcProvider, web_search

__all__ = [
    "AppConfig",
    "CodexConfig",
    "ModelProvider",
    "FallbackEvent",
    "GeoAliasSuggestion",
    "GeoScope",
    "ModelPreflight",
    "ModelPreflightError",
    "ModelProviderStatus",
    "ModelRequest",
    "ModelResponse",
    "OllamaNativeConfig",
    "OllamaOpenAIConfig",
    "OpenAIConfig",
    "ARTIFACT_SCHEMA_VERSION",
    "CitationValidationError",
    "EvidenceRecord",
    "Prospect",
    "ProspectCitation",
    "SearchEvidenceBatch",
    "SearchFailure",
    "SearchResult",
    "FirecrawlProvider",
    "YdcProvider",
    "build_artifact_payload",
    "build_model_client",
    "collect_search_evidence",
    "normalize_geography",
    "suggest_geography_alias_update",
    "CHECKPOINT_SCHEMA_VERSION",
    "GRAPH_TOPOLOGY",
    "GraphRunResult",
    "LocalCheckpointStore",
    "LocalResearchGraph",
    "ProspectRunBudget",
    "build_graph",
    "derive_prospect_run_budget",
    "graph",
    "inspect_thread",
    "resume_thread",
    "run_query",
    "load_config",
    "web_search",
]
